name: PHP Analysis
description: Run PHPStan static analysis
author: Candra Sudirman

inputs:
  php-version:
    description: PHP version to use
    required: false
    default: '8.2'
    type: string
  extensions:
    description: PHP extensions to install (comma-separated)
    required: false
    default: ''
    type: string
  composer-cmd:
    description: Composer command to install dependencies (install, update) with flags
    required: false
    default: install
    type: choice
    options:
      - install
      - update
  config:
    description: Path to PHPStan configuration file
    required: false
    default: 'phpstan.neon'
    type: string

runs:
  using: 'composite'
  steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        tools: phpstan
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.extensions }}

    - name: Validate composer.json and composer.lock
      run: composer validate
      shell: bash

    - name: Install Dependencies
      run: composer ${{ inputs.composer-cmd }} --prefer-dist --no-progress --no-interaction
      shell: bash

    - name: Run Static Analysis
      run: phpstan analyse --no-progress --configuration="${{ inputs.config }}"
      shell: bash