name: Update Changelog
description: Update the changelog file with recent changes
author: Candra Sudirman

inputs:
  branch:
    description: Branch to compare for recent changes
    required: false
    default: ${{ github.ref_name }}
    type: string
  changelog-file:
    description: Path to the changelog file
    required: false
    default: CHANGELOG.md
    type: string
  version:
    description: Version number to add to the changelog (e.g., v1.0.0)
    required: true
    type: string
  notes:
    description: Release notes to add to the changelog
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Check file exists
      if: ${{ hashFiles(inputs.changelog-file) == '' }}
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed(`Changelog file "${{ inputs.changelog-file }}" does not exist.`);

    - name: Extract release date from git tag
      id: release-date
      run: ${{ github.action_path }}/scripts/release-date.sh
      env:
        VERSION: ${{ inputs.version }}
      shell: bash
    
    - name: Update changelog
      uses: stefanzweifel/changelog-updater-action@v1
      with:
        release-date: ${{ steps.release-date.outputs.date }}
        release-notes: ${{ inputs.notes }}
        latest-version: ${{ inputs.version }}
        compare-url-target-revision: ${{ inputs.branch }}
        parse-github-usernames: true
    
    - name: Commit updated CHANGELOG
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: ${{ inputs.branch }}
        commit_message: Update CHANGELOG
        file_pattern: ${{ inputs.changelog-file }}